<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2011 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
//the left value is the key stored in the db and the right value is ie display value
//to translate, only modify the right value in each key/value pair
 $GLOBALS['app_list_strings']['kXML_list']=array ();
if($_REQUEST['module'] == 'Realty'){
include 'custom/modules/Realty/load_kxml_list.php';
$GLOBALS['app_list_strings']['kXML_list'];
}


$GLOBALS['app_list_strings']['contact_status_list']=array (
  'process' => 'в работе',
  'archive' => 'в архиве',
  'dont_contact' => 'не выходит на связь',
  'reject' => 'отказ от заявки',
);
$GLOBALS['app_list_strings']['request_status_new_list']=array (
  'process' => 'В работе',
  'closed_without_sell' => 'закрыта без продажи',
  'closed_with_sell' => 'закрыта с продажей',
);

$GLOBALS['app_list_strings']['contact_realship_list']=array (
  'rodnya' => 'родственник',
  'naslednik' => 'наследник',
  'dov_lico' => 'доверенное лицо',
);
$GLOBALS['app_list_strings']['room_layout_list']=array (
  0 => 'раздельные',
  1 => 'смежные',
  2 => 'смежно-раздельные',
);
$GLOBALS['app_list_strings']['h2o_list']=array (
  0 => 'централизованное',
  1 => 'автономное',
  2 => 'нет',
);
$GLOBALS['app_list_strings']['gaz_add_list']=array (
  0 => 'в доме',
  1 => 'по улице',
  2 => 'во дворе',
  3 => 'привозной',
  4 => 'у соседей',
  5 => 'на участке',
);
$GLOBALS['app_list_strings']['h2o_add_list']=array (
  0 => 'в доме',
  1 => 'по улице',
  2 => 'во дворе',
  3 => 'у соседей',
  4 => 'на участке',
);

$GLOBALS['app_list_strings']['kind_of_realty_list']=array (
	'flat' => 'Квартира',
	'room' => 'Комната',
	'house' => 'Дом',
	'stock' => 'Склад',
	'office' => 'Офис',
	'parcel' => 'Земельный участок',
	'gost' => 'Гостиннично-ресторанный комплекс',
	'poly' => 'многоцелевая',
	'torg' => 'Торговые площади',
	'sto' => 'СТО',
);


$GLOBALS['app_list_strings']['meeting_type_list']=array (
  'meeting' => 'встреча',
  'pokaz' => 'показ',
  'photo_pokaz' => 'фотопоказ',
);

$GLOBALS['app_list_strings']['state_of_object_list']=array (
  'major_repair' => 'Необходим капитальный ремонт',
  'cosmetic_repair' => 'Необходим косметический ремонт',
  'perfect' => 'Отличное',
  'eurorepair' => 'Евроремонт',
);
$GLOBALS['app_list_strings']['request_state_of_object_list']=array (
  '' => '',
  'major_repair' => 'Необходим капитальный ремонт',
  'cosmetic_repair' => 'Необходим косметический ремонт',
  'perfect' => 'Отличное',
  'eurorepair' => 'Евроремонт',
);
$GLOBALS['app_list_strings']['realty_status_list']=array (
  'realtor' => 'Риэлтор',
  'owner' => 'Владелец',
);
$GLOBALS['app_list_strings']['source_of_income_object_list']=array (
  'site' => 'Сайт',
  'advertisement' => 'Объявление',
  'realtor' => 'Риэлтор',
);
$GLOBALS['app_list_strings']['realty_currency_list']=array (
  'RUR' => 'Рубли',
  'USD' => 'Доллары',
  'EUR' => 'Евро',
  'UAH' => 'Гривны',
);
$GLOBALS['app_list_strings']['realty_period_list']=array (
  'day' => 'посуточная',
  'month' => 'помесячная',
  'year' => 'долгосрочная',
);
$GLOBALS['app_list_strings']['way_to_get_list']=array (
  'avto' => 'Авто',
  'on_foot' => 'Пешком',
);
$GLOBALS['app_list_strings']['operation_status_realty_list']=array (
  'in_rent' => 'В аренде',
  'out_rent' => 'Не в аренде',
  'bought' => 'Куплен',
  'not_bought' => 'Не куплен',
);
$GLOBALS['app_list_strings']['custom_parent_type_display']=array (
  'Accounts' => 'Юр.лица',
  'Contacts' => 'Физ.лица',
);
$GLOBALS['app_list_strings']['parent_type_display']=array (
  'Accounts' => 'Юр.лица',
  'Contacts' => 'Физ.лица',
);
$GLOBALS['app_list_strings']['square_unit_list']=array (
  'm2' => 'м2',
);
$GLOBALS['app_list_strings']['type_of_building_list']=array (
  'living' => 'Жилой дом',
  'commercial_object' => 'Коммерческий объект',
  'complex' => 'Комплекс',
);
$GLOBALS['app_list_strings']['sections_exist_list']=array (
  'yes' => 'Да',
  'no' => 'Нет',
);
$GLOBALS['app_list_strings']['custom_sales_stage_list']=array (
  'needs_analysis' => 'Анализ потребностей',
  'talks' => 'Переговоры',
  'conclusion_of_a_contract' => 'Заключение договора',
  'completed' => 'Oплата/закрыто с успехом',
  'denied' => 'Закрыто с отказом',
);
$GLOBALS['app_list_strings']['type_of_opportunity_list']=array (
  'realty' => 'Недвижимость',
  'client' => 'Клиент',
);
$GLOBALS['app_list_strings']['type_of_contract_list']=array (
  'rent' => 'обычный',
  'buying' => 'эксклюзивный',
);

$app_strings['LBL_TABGROUP_SALES'] = 'Клиенты';

$app_strings['LBL_TABGROUP_SUPPORT'] = 'Объекты';

$app_strings['LBL_TABGROUP_COLLABORATION'] = 'Сделки';

$app_strings['LBL_GROUPTAB3_1359244505'] = 'Договоры';

$app_strings['LBL_GROUPTAB6_1359244525'] = 'Отчеты';
$app_list_strings['sugartalk_sms_module_selected_list']=array (
  '-BLANK-' => '-BLANK-',
  'Accounts' => 'Юр.лица',
  'Contacts' => 'Физ.лица',
  'Realty' => 'Объекты недвижимости',
);
$app_strings['LBL_GROUPTAB7_1360746066'] = 'Почта';

$GLOBALS['app_list_strings']['su_list']=array (
  1 => 'Совмещ',
  2 => 'разд',
);
$app_list_strings['moduleList']['Sections']='Подъезды';
$app_list_strings['moduleListSingular']['Sections']='Подъезд';
$GLOBALS['app_list_strings']['type_of_realty_list']=array (
  'living' => 'Жилая',
  'not_living' => 'Коммерческая',
  'parcel' => 'Земельный участок',
);
$app_list_strings['moduleListSingular']['Contacts']='Физ.лицо';
$app_list_strings['moduleListSingular']['Accounts']='Юр.лицо';
$app_list_strings['parent_type_display']['Contacts']='Физ.лицо';
$app_list_strings['parent_type_display']['Accounts']='Юр.лицо';


$app_list_strings['moduleList']['Documents']='Вложения';
$app_list_strings['moduleListSingular']['Documents']='Вложения';
$GLOBALS['app_list_strings']['contact_type_list']=array (
  'client' => 'Клиент',
  'owner' => 'Владелец',
);
$app_list_strings['moduleList']['Meetings']='Встречи/показы';
$app_list_strings['moduleListSingular']['Meetings']='Встреча/показ';
$app_list_strings['moduleList']['Realty']='Недвижимость';
$app_list_strings['moduleListSingular']['Realty']='Недвижимость';
$GLOBALS['app_list_strings']['activity_status_list']=array (
  'active' => 'Активен',
  'no_active' => 'Не активен',
);
$GLOBALS['app_list_strings']['operation_realty_list']=array (
  'rent' => 'Аренда',
  'buying' => 'Продажа',
  '' => '',
);
$GLOBALS['app_list_strings']['gaz_list']=array (
  0 => 'централизованное',
  1 => 'автономное',
  2 => 'нет',
);
$GLOBALS['app_list_strings']['motivation_status_list']=array (
  'reasoned' => 'Мотивированный',
  'unreasoned' => 'Немотивированный',
);
$GLOBALS['app_list_strings']['mark_objective_list']=array (
  1 => '1',
);
$GLOBALS['app_list_strings']['request_status_list']=array (
  'not_started' => 'Не начата',
  'complete' => 'Выполнена',
  'canceled' => 'Отменена',
  'in_work' => 'В работе',
  'paused' => 'Пауза',
);
$app_strings['LBL_GROUPTAB1_1395386407'] = 'Заявки';

$app_strings['LBL_GROUPTAB1_1395386408'] = 'Заявки';

$app_list_strings['moduleList']['Contract']='Договоры';
$app_list_strings['moduleListSingular']['Contract']='Договор';
$app_strings['LBL_GROUPTAB2_1395839446'] = 'Заявки';

$GLOBALS['app_list_strings']['source_contact_list']=array (    
  '' => '',
  '0' => 'Рекомендации знакомых',
  '1' => 'Контекстная реклама',
  '2' => 'Порталы по  недвижимости',
  '3' => 'e-mail - рассылки',
  '4' => 'Социальные сети',
  '5' => 'Форумы',
  '6' => 'Печатная реклама (флаеры, буклеты)',
  '7' => 'Выставки, конференции',
  '8' => 'Печатные СМИ',
  '9' => 'Наружная реклама',
);

?>